<?php

namespace BateauxBundle\Repository;

/**
 * bateauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bateauRepository extends \Doctrine\ORM\EntityRepository
{
}
